FROM openjdk:14-alpine AS builder

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN chmode +x ./gradlew
RUN ./gradlew bootJar

FROM openjdk:14-alpine
COPY --from=builder build/libs/*.jar app.jar


EXPOSE 8080

ENTRYPOINT ["java", "-Dspring.profile.active=dev", "-jar", "/app.jar"]

