version: "3"

services:
  redis_dev:
    image: redis
    ports:
      - "6379:6379"
  bank_system_dev:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis_dev


