version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  bank_system:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8080"
    depends_on:
      - redis


