spring:
  redis:
    host: redis_dev
    port: 6379
    password:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  datasource:
    url: jdbc:h2:tcp://10.10.100.231/~/bankSystem
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
    locale: en
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  error:
    include-stacktrace: never
    include-binding-errors: never